[params]
title = "Adventures of Tofticles"
author = "Magnus Toftdal"
description = """There are no silver bullets! 
Here, have mine
"""
profilePicture = "images/tofticles.jpg"
contentratio = 0.8
hidesidebar = true
reversepagetitle = true
customCss = ["css/custom.css"]
mainSections = ["2023", "2024"]

[[params.socialIcons]]
icon = "fa-brands fa-mastodon"
title = "mastodon"
url = "https://helvede.net/@tofticles"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/magnus-toftdal/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:toftdal@hey.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "RSS"
  identifier = "rss"
  weight = 120
  url = "/index.xml"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 140
  url = "/about"

